module.exports = {
  someSidebar: [
    'dedication',
    {
      'Chicky Taylor Stories (1990-2000)': [
        'chickytaylor/introduction',
        'chickytaylor/first-time',
        'chickytaylor/the-tunnel',
        'chickytaylor/little-league',
        'chickytaylor/heinekens',
        'chickytaylor/home-run',
        'chickytaylor/ketchup',
        'chickytaylor/cookie-dough',
      ],
      'Turkey, Thailand, Laos, New Zealand (2014)': [
        'fall14/introduction',
        'fall14/suitcase-or-wheelie',
        'fall14/ranger-rolling',
        'fall14/first-stop',
        'fall14/four-generations',
        'fall14/tea-sugar',
        'fall14/verkin',
        'fall14/cappadocia',
        'fall14/call-to-prayer',
        'fall14/fire-on-the-mountain',
        'fall14/haircut',
        'fall14/joanne',
        'fall14/farewell-turkey',
        'fall14/completely-different',
        'fall14/mild',
        'fall14/ask',
        'fall14/apocalypse',
        'fall14/goodbye-asia',
        'fall14/cousins',
        'fall14/lotr',
        'fall14/south',
      ],
      'Bhutan (2018)': [
        'bhutan/introduction',
        'bhutan/bhutan1',
        'bhutan/bhutan2',
        'bhutan/bhutan3',
        'bhutan/bhutan4',
      ],
      'Bands': [
        'bands/east-west-journal',
        'bands/mabanzi',
        'bands/shakadown',
        'bands/hsj',
        'bands/phish',
        'bands/filks',
      ],
      'Events': [
        'events/doris-is-80',
        'events/jazzfest',
        'events/kahala-challenge',
        'events/doris-is-90',
        'events/larry-first-dead-show',
      ],
    },
    'videos',
    {
      'Miscellaneous': [
        'misc/philip-early-years',
        'misc/pbj',
      ],
    },
  ],
};
